import React from "react";
import Header from "../components/Header";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import MyButton from "../UI/MyButton";
import SectionForm from "../components/SectionForm";
import Footer from "../components/Footer";
const acceptance = () => {
  return (
    <>
      <Head>
        <title>Услуги</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="servicesBgAcceptance bgSettings">
        <Header />
        <div className="container">
          <div className="bredcrumb mt-12">
            <div className="text-white text-xs uppercase flex items-center">
              <Link href="/">Главная</Link>
              <div className=" mx-2">
                <Image
                  src="/breadcrumb arrow-right.svg"
                  width={12.5}
                  height={8}
                />
              </div>
              <Link href="/">Услуги</Link>
              <div className=" mx-2">
                <Image
                  src="/breadcrumb arrow-right.svg"
                  width={12.5}
                  height={8}
                />
              </div>

              <Link href="/services/acceptance">приемка квартир и домов</Link>
            </div>
          </div>
          <h1 className="text-white uppercase title max-w-2xl mt-9 mb-7">
            Профессиональная приемка квартир и домов у застpойщика
          </h1>

          <div className="flex items-center text-white mb-5">
            <div className=" w-2  h-5 bg-red mr-7"></div>
            <div>
              Поможем проверить объект нa соответcтвиe дeйcтвующим строитeльным
              ноpмaтивам
            </div>
          </div>

          <div className="flex items-center text-white mb-5">
            <div className=" w-2  h-5 bg-red mr-7"></div>
            <div>Предоставим заключение специалиста в течении 24 часов</div>
          </div>

          <div className="flex items-center text-white  mb-12">
            <div className=" w-2  h-5 bg-red mr-7"></div>
            <div>Осуществим технический надзор за строительством</div>
          </div>

          <MyButton>Получить консультацию</MyButton>
        </div>
      </div>

      <section className="benefits py-40">
        <div className="container">
          <div className="flex justify-between">
            <h1 className="sectionTitle mb-14 max-w-2xl">
              Преимущества сотрудничества с нашей компанией
            </h1>
            <p className="text-textColor ">
              Отличительная черта работы нашей компании – безупречное качество,
              которое проходит многоступенчатый контроль.
            </p>
          </div>

          <div className="flex justify-between items-center mb-16">
            <div className="item w-2/4">
              <div className="flex">
                <span className="text-red font-bold text-xl mr-2">01</span>
                <p>/</p>
                <h3 className="text-titleColor font-bold text-xl ml-2 ">
                  12+ лет – стаж работы
                </h3>
              </div>
              <p className="text-textColor font-medium">
                Наш инженер-строитель - имеет 2 строительных <br /> образования,
                квалификацию технического надзора
              </p>
            </div>

            <div className="item w-2/4">
              <div className="flex">
                <span className="text-red font-bold text-xl mr-2">02</span>
                <p>/</p>
                <h3 className="text-titleColor font-bold text-xl ml-2 ">
                  Помощь на любом этапе
                </h3>
              </div>
              <p className="text-textColor font-medium">
                Принимаем активное участие во всех процессах, <br /> включая
                юридическую поддержку и представление ваших интересов в суде
              </p>
            </div>
          </div>

          <div className="flex justify-between items-center mb-16">
            <div className="item w-2/4">
              <div className="flex">
                <span className="text-red font-bold text-xl mr-2">03</span>
                <p>/</p>
                <h3 className="text-titleColor font-bold text-xl ml-2 ">
                  Точный замер площади
                </h3>
              </div>
              <p className="text-textColor font-medium">
                Производим замер площади обследуемого <br /> объекта
                высокоточным оборудованием
              </p>
            </div>

            <div className="item w-2/4">
              <div className="flex">
                <span className="text-red font-bold text-xl mr-2">04</span>
                <p>/</p>
                <h3 className="text-titleColor font-bold text-xl ml-2 ">
                  Высокая репутация
                </h3>
              </div>
              <p className="text-textColor font-medium">
                Имеем множество положительных отзывов <br /> клиентов,
                насыщенное портфолио и ресурсы для решения неординарных задач
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className=" py-36 bg-formColor relative">
        <div className="container">
          <div className="  w-1/3">
            <h2 className=" text-4xl leading-snug font-bold text-white  mb-9">
              Что входит в приемку квартиры?
            </h2>
            <p className="text-white mb-20">
              Наш эксперт проверит на соответствие строительным нормам следующие
              элементы:
            </p>
            <div className="border-2 border-red absolute left-0  w-2/4 z-10"></div>
          </div>

          <div className="flex absolute top-52 right-0">
            <div className=" bg-colorGrey w-96 mr-8  py-7  px-14">
              <div className="flex">
                <div className=" w-2  h-5 bg-red mr-4"></div>
                <h4 className="text-white uppercase font-bold mb-4">
                  ИНЖЕНЕРНЫЕ СЕТИ
                </h4>
              </div>
              <p className="text-grey">
                Водоснабжение, электроснабжение, системы отопления и вентиляции
              </p>
            </div>

            <div className=" bg-colorGrey w-96 mr-8  py-7  px-14">
              <div className="flex">
                <div className=" w-2  h-5 bg-red mr-4"></div>
                <h4 className="text-white uppercase font-bold mb-4">ОТДЕЛКА</h4>
              </div>
              <p className="text-grey">
                Ремонт чистовой и предчистовой, напольное и настенное покрытие,
                потолок, сантехника и т. д
              </p>
            </div>
          </div>

          <div className="flex pt-16">
            <div className=" bg-colorGrey w-96 mr-8  py-7  px-14">
              <div className="flex">
                <div className=" w-2  h-5 bg-red mr-4"></div>
                <h4 className="text-white uppercase font-bold mb-4">
                  ЖЕЛЕЗО-БЕТОННЫЕ КОНСТРУКЦИИ
                </h4>
              </div>
              <p className="text-grey">Стены, пол, потолок</p>
            </div>

            <div className=" bg-colorGrey w-96 mr-8  py-7  px-14">
              <div className="flex">
                <div className=" w-2  h-5 bg-red mr-4"></div>
                <h4 className="text-white uppercase font-bold mb-4">
                  ПЛОЩАДЬ КВАРТИРЫ
                </h4>
              </div>
              <p className="text-grey">Проведение контрольного обмера</p>
            </div>

            <div className=" bg-colorGrey w-96 mr-8  py-7  px-14">
              <div className="flex">
                <div className=" w-2  h-5 bg-red mr-4"></div>
                <h4 className="text-white uppercase font-bold mb-4">
                  ОКОННЫЕ И ДВЕРНЫЕ БЛОКИ
                </h4>
              </div>
              <p className="text-grey">
                Блок - это совокупность всех элементов изделия
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className=" py-40">
        <div className="container">
          <div className="flex">
            <Image
              src="/services/acceptance/img-1.png"
              width={491}
              height={680}
            />
            <div>
              <div className="ml-20">
                <h2 className="sectionTitle mb-5">
                  По результатам обследования квартиры
                </h2>
                <p className=" font-semibold text-lg text-titleColor mb-12">
                  специалистом с опытом работы более 12 лет
                </p>
              </div>

              <div className="bg-titleColor">
                <div className=" py-14  pl-20 text-white max-w-xl mb-12">
                  <div className="flex">
                    <div className=" w-2  h-5 bg-red mr-4"></div>
                    <p className=" mb-8">
                      Составляем акт технического осмотра с перечислением всех
                      выявленных нарушений.
                    </p>
                  </div>

                  <div className="flex">
                    <div className=" w-2  h-5 bg-red mr-4"></div>
                    <p className=" mb-8">
                      Вместе с вами подаем акт Застройщику, чтобы были соблюдены
                      все формальности, и на наш Акт осмотра точно обратил
                      внимание Застройщик.
                    </p>
                  </div>
                </div>
              </div>
              <div className="ml-20">
                <MyButton>Получить консультацию</MyButton>
              </div>
            </div>
          </div>
        </div>
      </section>

      <div>Объекты, которые мы помогли принять</div>
      <div>Стоимость услуг</div>
      <div>Оборудование Hilti, с которым мы работаем</div>
      <div>Ответы на вопросы</div>
      <SectionForm/>
      <Footer/>
    </>
  );
};

export default acceptance;
