import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import Link from "next/link";
import Image from "next/image";
import MyButton from "../UI/MyButton";

const finishWork = () => {
  return (
    <>
      <Head>
        <title>Услуги</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="servicesBgFinish bgSettings">
        <Header />
        <div className="container">
          <div className="bredcrumb mt-12">
            <div className="text-white text-xs uppercase flex items-center">
              <Link href="/">Главная</Link>
              <div className=" mx-2">
                <Image
                  src="/breadcrumb arrow-right.svg"
                  width={12.5}
                  height={8}
                />
              </div>
              <Link href="/">Услуги</Link>
              <div className=" mx-2">
                <Image
                  src="/breadcrumb arrow-right.svg"
                  width={12.5}
                  height={8}
                />
              </div>

              <Link href="/services/acceptance">Ремонтно-отделочные работы</Link>
            </div>
          </div>
          <h1 className="text-white uppercase title  max-w-xl mt-9 mb-7">
            Ремонтно-отделочные работы
          </h1>

          <div className="flex items-center text-white mb-5">
            <div className=" w-2  h-5 bg-red mr-7"></div>
            <div>
            100+ выполненных работ по дизайн-проектам
            </div>
          </div>

          <div className="flex items-center text-white mb-5">
            <div className=" w-2  h-5 bg-red mr-7"></div>
            <div>13 лет опыта работы в строительстве</div>
          </div>

          <div className="flex items-center text-white  mb-12">
            <div className=" w-2  h-5 bg-red mr-7"></div>
            <div>Работа с готовыми проектами и ремонт под ключ</div>
          </div>

          <MyButton>Получить консультацию</MyButton>
        </div>
      </div>
    </>
  );
};

export default finishWork;
