import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import Link from "next/link";
import Image from "next/image";
import MyButton from "../UI/MyButton";
import SectionForm from "../components/SectionForm";
import Footer from "../components/Footer";

const measurment = () => {
  return (
    <>
      <Head>
        <title>Услуги</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="servicesBgMeasurment bgSettings">
        <Header />
        <div className="container">
          <div className="bredcrumb mt-12">
            <div className="text-white text-xs uppercase flex items-center">
              <Link href="/">Главная</Link>
              <div className=" mx-2">
                <Image
                  src="/breadcrumb arrow-right.svg"
                  width={12.5}
                  height={8}
                />
              </div>
              <Link href="/">Услуги</Link>
              <div className=" mx-2">
                <Image
                  src="/breadcrumb arrow-right.svg"
                  width={12.5}
                  height={8}
                />
              </div>

              <Link href="/services/acceptance">
                Технический замер помещений{" "}
              </Link>
            </div>
          </div>
          <h1 className="text-white uppercase title mt-16 mb-7  max-w-xl">
            Технический замер помещений
          </h1>

          <MyButton>Получить консультацию</MyButton>
        </div>
      </div>

      <section className="benefits py-40">
        <div className="container">
          <div className="flex justify-between">
            <h1 className="sectionTitle mb-14 max-w-2xl">
              Преимущества сотрудничества с нашей компанией
            </h1>
            <p className="text-textColor ">
              Отличительная черта работы нашей компании – безупречное качество,
              которое проходит многоступенчатый контроль.
            </p>
          </div>

          <div className="flex justify-between items-center mb-16">
            <div className="item w-2/4">
              <div className="flex">
                <span className="text-red font-bold text-xl mr-2">01</span>
                <p>/</p>
                <h3 className="text-titleColor font-bold text-xl ml-2 ">
                  12+ лет – стаж работы
                </h3>
              </div>
              <p className="text-textColor font-medium">
                Наш инженер-строитель - имеет 2 строительных <br /> образования,
                квалификацию технического надзора
              </p>
            </div>

            <div className="item w-2/4">
              <div className="flex">
                <span className="text-red font-bold text-xl mr-2">02</span>
                <p>/</p>
                <h3 className="text-titleColor font-bold text-xl ml-2 ">
                  Помощь на любом этапе
                </h3>
              </div>
              <p className="text-textColor font-medium">
                Принимаем активное участие во всех процессах, <br /> включая
                юридическую поддержку и представление ваших интересов в суде
              </p>
            </div>
          </div>

          <div className="flex justify-between items-center mb-16">
            <div className="item w-2/4">
              <div className="flex">
                <span className="text-red font-bold text-xl mr-2">03</span>
                <p>/</p>
                <h3 className="text-titleColor font-bold text-xl ml-2 ">
                  Точный замер площади
                </h3>
              </div>
              <p className="text-textColor font-medium">
                Производим замер площади обследуемого <br /> объекта
                высокоточным оборудованием
              </p>
            </div>

            <div className="item w-2/4">
              <div className="flex">
                <span className="text-red font-bold text-xl mr-2">04</span>
                <p>/</p>
                <h3 className="text-titleColor font-bold text-xl ml-2 ">
                  Высокая репутация
                </h3>
              </div>
              <p className="text-textColor font-medium">
                Имеем множество положительных отзывов <br /> клиентов,
                насыщенное портфолио и ресурсы для решения неординарных задач
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="exampleWork bg-formColor py-36">
        <div className="container">
          <h1 className=" font-bold text-4xl text-white mb-12 text-center">
            Примеры наших работ
          </h1>
          <div className="flex justify-between items-center">
            <div className=" mr-8 hover:scale-110 transition-all cursor-pointer relative ">
              <Image
                src="/services/example-work.png"
                width={386}
                height={340}
              />
              <div className="flex items-center absolute bottom-0 w-60 pb-6">
                <div className=" w-2  h-5 bg-red mr-4  "></div>
                <p className=" text-titleColor font-medium transparent">
                  1-комнатная квартира в ЖК “Молодежный”
                </p>
              </div>
            </div>
            <div className="mr-8 hover:scale-110 transition-all cursor-pointer relative">
              <Image
                src="/services/example-work.png"
                width={386}
                height={340}
              />
              <div className="flex items-center absolute bottom-0 w-60 pb-6">
                <div className=" w-2  h-5 bg-red mr-4  "></div>
                <p className=" text-titleColor font-medium transparent">
                  1-комнатная квартира в ЖК “Молодежный”
                </p>
              </div>
            </div>
            <div className="mr-8 hover:scale-110 transition-all cursor-pointer relative">
              <Image
                src="/services/example-work.png"
                width={386}
                height={340}
              />
              <div className="flex items-center absolute bottom-0 w-60 pb-6">
                <div className=" w-2  h-5 bg-red mr-4  "></div>
                <p className=" text-titleColor font-medium transparent">
                  1-комнатная квартира в ЖК “Молодежный”
                </p>
              </div>
            </div>
          </div>
          <div className="text-center  mt-11">
            <MyButton>Получить консультацию</MyButton>
          </div>
        </div>
      </section>

      <section className=" py-40 relative">
        <div className="container">
          <h2 className="sectionTitle mb-9">Что вы получаете?</h2>
          <div className="border-2 border-red mb-14 absolute left-0  w-3/4 z-10"></div>
          <div className="flex">
            <div className=" mt-14">
              <div className="flex  mb-6">
                <div className=" w-2  h-5 bg-red mr-4  "></div>
                <p>Отчерченый план в DWG (автокад и архикад) и PDF</p>
              </div>

              <div className="flex  mb-6">
                <div className=" w-2  h-5 bg-red mr-4  "></div>
                <p>Привязка всех дверей, окон, ниш, выступов.</p>
              </div>

              <div className="flex  mb-6">
                <div className=" w-2  h-5 bg-red mr-4  "></div>
                <p>Привязка высот окон, подоконников, дверей, потолков.</p>
              </div>

              <div className="flex  mb-6">
                <div className=" w-2  h-5 bg-red mr-4  "></div>
                <p>Привязка радиаторов и труб</p>
              </div>

              <div className="flex  mb-6">
                <div className=" w-2  h-5 bg-red mr-4  "></div>
                <p>Привязка стояка с отдельной привязкой каждой трубы</p>
              </div>

              <div className="flex  mb-6">
                <div className=" w-2  h-5 bg-red mr-4  "></div>
                <p>Привязка электрических щитов.</p>
              </div>

              <div className="flex  mb-6">
                <div className=" w-2  h-5 bg-red mr-4  "></div>
                <p>
                  При возможности отмечаются несущии конструкции и перегородки
                </p>
              </div>

              <div className="flex  mb-6">
                <div className=" w-2  h-5 bg-red mr-4  "></div>
                <p>Фото-видеофиксация</p>
              </div>
            </div>
            <div className="absolute  top-24  right-52">
              <Image src="/services/img.png" width={491} height={624} />
            </div>
          </div>
        </div>
      </section>

      <div>Ответы на вопросы</div>
      <SectionForm/>
      <Footer/>
    </>
  );
};

export default measurment;
