import React from "react";
import Header from "./components/Header";
import Head from "next/head";
import SectionForm from "./components/SectionForm";
import Footer from "./components/Footer";
import Link from "next/link";
import Image from "next/image";

const contact = () => {
  return (
    <>
      <Head>
        <title>Контакты</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="equipmentBg bgSettings">
        <Header />
        <div className="container">
          <div className="bredcrumb mt-12">
            <div className="text-white text-xs uppercase flex items-center">
              <Link href="/">Главная</Link>
              <div className=" mx-2">
                <Image
                  src="/breadcrumb arrow-right.svg"
                  width={12.5}
                  height={8}
                />
              </div>
              <Link href="/equipment">Оборудования</Link>
            </div>
          </div>
          <h1 className="text-white uppercase title  mb-7 max-w-2xl">
            Контакты
          </h1>
        </div>
      </div>

      <section className=" pt-6 pb-40 relative flex">
        <iframe
          className=" mr-7 ml-12"
          src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d9183.65913805193!2d71.43101189074038!3d51.13220870779667!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2skz!4v1676287407419!5m2!1sru!2skz"
          width="719"
          height="719"
        ></iframe>
        <div className="flex">
          <div>
            <h2 className=" text-5xl leading-10 font-medium text-titleColor mb-14">
              Контакты
            </h2>
            <div className="border-b-4 border-red absolute right-0 top-11 w-96"></div>
            <p className=" text-2xl text-titleColor  mb-14 font-medium">
              Город: Астана
            </p>
            <div className="flex justify-between items-center text-lg leading-6 text-titleColor  mb-20">
              <div className="flex">
                <Image src="/clock.svg" width={35} height={35} />
                <div className=" ml-4">
                  <p>Офис</p>
                  <p className=" font-bold">09:00 - 18:00</p>
                </div>
              </div>

              <div className="flex">
                <Image src="/map-pin.svg" width={35} height={35} />
                <div className=" ml-4">
                  <p>Адрес офиса</p>
                  <p> ул. Есильская, 9, 010000</p>
                </div>
              </div>
            </div>

            <div className="flex justify-between items-center text-lg leading-6 text-titleColor  mb-20">
              <Image src="/phone-call.svg" width={35} height={35} />
              <div className=" ml-4 mr-24">
                <p>Прием заявок</p>
                <div>
                  <a href="tel:+7 (4012) 92-22-15">+7 (4012) 92-22-15</a>
                </div>
                <div>
                  <a href="tel:+7 (4012) 92-22-15">+7 (4012) 92-22-15</a>
                </div>
              </div>

              <div className="flex">
                <Image src="/mail.svg" width={35} height={35} />
                <div className=" ml-4">
                  <a href="mailto:office@stroyeproekt.kz">
                    office@stroyeproekt.kz
                  </a>
                </div>
              </div>
            </div>

            <div>
              <p>Связаться с нами</p>
              <div className="flex">
                <div className="mt-5 mr-6">
                  <Image src="/facebook.svg" width={35} height={35} />
                </div>
                <div className="mt-5 mr-6">
                  <Image src="/whatsapp.svg" width={35} height={35} />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <SectionForm />
      <Footer />
    </>
  );
};

export default contact;
