import Head from "next/head";
import Header from "./components/Header";
import Image from "next/image";
import MyButton from "./UI/MyButton";
import SectionForm from "./components/SectionForm";
import Footer from "./components/Footer";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className="mainBg BgSettings ">
        <Header />
        <div className="main__title">
          <div className="container relative">
            <h1 className="mainTitle mt-20 mb-8">
              Профессионализм <br /> и креативность
            </h1>

            <p className="text">
              наши главные, но не единственный преимущества
            </p>

            <p className="text absolute  right-0 top-7  transform rotate-90">
              первые на рынке
            </p>

            <div className="flex justify-between">
              <div className="">
                <button>
                  <div className="bg-white py-4 px-3  mt-14" >
                    <Image src="/Arrow - Right.svg" width={37} height={24} />
                  </div>
                </button>
              </div>
              <div className="text border border-white text-center">
                <div className=" px-8 py-12">
                  <span className="text-5xl block mb-2">14+</span>
                  <p>лет опыта</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <section className="offer  my-32 ">
        <div className="container">
          <h1 className="sectionTitle">Мы предлагаем</h1>
          <div className="offer__items flex justify-between items-center mt-5 ">
            <div className="offer__item  ">
              <div className="flex">
                <span className="text-red  font-bold">01 </span>
                <span className=" mx-2">/</span>
                <div className=" font-bold uppercase mb-4 text-titleColor">
                  {" "}
                  Проектирование
                </div>
              </div>
              <p className=" text-textColor">
                Качественные архитектурные проекты
              </p>
            </div>

            <div className="offer__item">
              <div className="flex">
                <span className="text-red  font-bold ">02</span>
                <span className=" mx-2">/</span>

                <div className=" font-bold uppercase mb-4 text-titleColor">
                  Отделочные работы
                </div>
              </div>
              <p className=" text-textColor">
                Качественные архитектурные проекты
              </p>
            </div>

            <div className="offer__item">
              <div className="flex">
                <span className="text-red  font-bold">02</span>
                <span className=" mx-2">/</span>

                <div className=" font-bold uppercase mb-4 text-titleColor">
                  Отделочные работы
                </div>
              </div>
              <p className=" text-textColor">
                Качественные архитектурные проекты
              </p>
            </div>

            <div className="offer__item">
              <div className="flex">
                <span className="text-red  font-bold">04</span>
                <span className=" mx-2">/</span>

                <div className=" font-bold uppercase mb-4 text-titleColor">
                  Согласование
                </div>
              </div>
              <p className=" text-textColor">
                Качественные архитектурные проекты
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="about__company aboutBg  py-32 ">
        <div className="container">
          <div className="company__inner flex justify-between">
            <h2 className="sectionTitle">О компании</h2>
            <div className="flex  w-3/4 text-textColor">
              <div className="">
                Компания основана в 2009 году и осуществляет все виды отделочных
                работ как для коммерческих объектов, так и для объектов
                социально значимого плана.
                <div>
                  {" "}
                  <br />
                  Отличительная черта работы нашей компании – безупречное
                  качество, которое проходит многоступенчатый контроль.
                </div>
              </div>
              <div>
                Компания основана в 2009 году и осуществляет все виды отделочных
                работ как для коммерческих объектов, так и для объектов
                социально значимого плана.
                <div>
                  {" "}
                  <br />
                  Отличительная черта работы нашей компании – безупречное
                  качество, которое проходит многоступенчатый контроль.
                </div>
              </div>
            </div>
          </div>
          <div className="text-center mt-14">
            <MyButton>
              <Link href="/about">Узнать больше</Link>
            </MyButton>
          </div>
        </div>
      </section>

      <section className="services  py-32">
        <div className="container">
          <div className="flex">
            <div>
              <h3 className="sectionTitle mb-7">Услуги</h3>
              <p className="text-textColor w-72">
                {" "}
                Отличительная черта работы нашей компании – безупречное
                качество, которое проходит многоступенчатый контроль.
              </p>
            </div>

            <div className="first__items flex">
              <div className="first__item mr-7  mb-7">
                <div className="relative">
                  <Image src="/main/services/1.png" width={282} height={387} />
                  <div className="absolute bottom-0  w-52  h-16 bg-white ">
                    <div className="flex m-2">
                      <div className=" absolute left-0 w-2 h-5 bg-red pr-2"></div>
                      <p className="ml-2 text-titleColor">
                        Приемка квартир и домов у застройщика
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="first__item mr-7">
                <div className="relative">
                  <Image src="/main/services/1.png" width={282} height={387} />
                  <div className="absolute bottom-0  w-52  h-16 bg-white ">
                    <div className="flex m-2">
                      <div className=" absolute left-0 w-2 h-5 bg-red pr-2"></div>
                      <p className="ml-2 text-titleColor">
                        Архитектурное проектирование
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="first__item mr-7 relative">
                <div className="relative">
                  <Image src="/main/services/1.png" width={282} height={387} />
                  <div className="absolute bottom-0  w-52  h-16 bg-white ">
                    <div className="flex m-2">
                      <div className=" absolute left-0 w-2 h-5 bg-red pr-2"></div>
                      <p className="ml-2 text-titleColor">
                        Профессиональное алмазное бурение
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="second__items flex">
            <div className="second__item  mr-8">
              <div className="relative">
                <Image src="/main/services/2.png" width={385} height={367} />
                <div className="absolute bottom-0  w-52  h-16 bg-white ">
                  <div className="flex m-2">
                    <div className=" absolute left-0 w-2 h-5 bg-red pr-2"></div>
                    <p className="ml-2 text-titleColor">
                      Согласование документовие
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="second__item mr-8">
              <div className="relative">
                <Image src="/main/services/2.png" width={385} height={367} />
                <div className="absolute bottom-0  w-52  h-16 bg-white ">
                  <div className="flex m-2">
                    <div className=" absolute left-0 w-2 h-5 bg-red pr-2"></div>
                    <p className="ml-2 text-titleColor">
                      Технический замер помещений
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="second__item">
              <div className="relative">
                <Image src="/main/services/2.png" width={385} height={367} />
                <div className="absolute bottom-0  w-52  h-16 bg-white ">
                  <div className="flex m-2">
                    <div className=" absolute left-0 w-2 h-5 bg-red pr-2"></div>
                    <p className="ml-2 text-titleColor">
                      Ремонтно-отделочные работы
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="advantages advantagesBg bgSettings">
        <div className="container">
          <div className=" py-24 flex">
            <Image src={"/main/advantages-card.png"} width={491} height={680} />
            <div className=" max-w-2xl ml-16">
              <h2 className="text-white text-4xl font-bold mb-11">
                Преимущества
              </h2>

              <div className="item flex">
                <div className=" max-w-xs">
                  <div className="flex relative">
                    <span className="text-red font-bold  mr-4">01</span>
                    <div className="bg-white  h-20 w-px absolute left-3 top-8"></div>
                    <h4 className=" text-sm  font-semibold uppercase mb-4 text-white">
                      Страхование объекта <br /> в подарок
                    </h4>
                  </div>
                  <p className="text-sm text-grey ml-10 mb-10  w-64">
                    Для клиентов из других регионов, не имеющих возможность
                    лично контролировать процесс работ, наша компания, имея
                    большой опыт работы с удаленными клиентами, обеспечит вам
                    возможность дистанционно влиять на ход и результат работ.
                  </p>
                </div>

                <div className="max-w-xs">
                  <div className="flex relative">
                    <span className="text-red font-bold  mr-4">02</span>
                    <div className="bg-white  h-20 w-px absolute left-3 top-8"></div>
                    <h4 className=" text-sm  font-semibold uppercase mb-4 text-white">
                      Комплексный подход и раширенная гарантия
                    </h4>
                  </div>

                  <p className="text-sm text-grey ml-10 mb-10 w-64">
                    Для клиентов из других регионов, не имеющих возможность
                    лично контролировать процесс работ, наша компания, имея
                    большой опыт работы с удаленными клиентами, обеспечит вам
                    возможность дистанционно влиять на ход и результат работ.
                  </p>
                </div>
              </div>

              <div className="item flex">
                <div className=" max-w-xs">
                  <div className="flex relative">
                    <span className="text-red font-bold  mr-4">03</span>
                    <div className="bg-white  h-20 w-px absolute left-3 top-8"></div>
                    <h4 className=" text-sm  font-semibold uppercase mb-4 text-white">
                      Страхование объекта в подарок
                    </h4>
                  </div>
                  <p className="text-sm text-grey ml-10 mb-10 w-64">
                    Для клиентов из других регионов, не имеющих возможность
                    лично контролировать процесс работ, наша компания, имея
                    большой опыт работы с удаленными клиентами, обеспечит вам
                    возможность дистанционно влиять на ход и результат работ.
                  </p>
                </div>

                <div className="max-w-xs">
                  <div className="flex relative">
                    <span className="text-red font-bold  mr-4">04</span>
                    <div className="bg-white  h-20 w-px absolute left-3  top-8"></div>
                    <h4 className=" text-sm  font-semibold uppercase mb-4 text-white">
                      Комплексный подход и раширенная гарантия
                    </h4>
                  </div>

                  <p className="text-sm text-grey ml-10 mb-10 w-64">
                    Для клиентов из других регионов, не имеющих возможность
                    лично контролировать процесс работ, наша компания, имея
                    большой опыт работы с удаленными клиентами, обеспечит вам
                    возможность дистанционно влиять на ход и результат работ.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

   <div>Об основателе</div>

      <SectionForm />

      <Footer />
    </>
  );
}
